### ISSUE TITLE
Dist::Build tries to generate man pages even when running on a Perl that was built with man page generation disabled.

### ISSUE THREAD

**Issue by skaji** [Leont/dist-build#10]
# Problem

Dist::Build tries to generate man pages even when running on a Perl that was built with man page generation disabled.

# Steps to reproduce

Please see https://github.com/skaji/perl-dist-build-test

# Note

For reference, ExtUtils::MakeMaker, Module::Build, and Module::Build::Tiny do not generate man pages when running on a Perl built with man page generation disabled.

**Comment by Leont** [comment]
Yeah that's an oversight. It should be fixed in 0.021

**Comment by skaji** [comment]
@Leont Thanks for working on this issue.
Unfortunately, even with Dist::Build 0.021 I’m still seeing the warning `WARNING: Can't figure out install path for types: libdoc bindoc`:

```
❯ perl -MDist::Build\ 99999
Dist::Build version 99999 required--this is only version 0.021.
BEGIN failed--compilation aborted.

❯ perl Build.PL
Creating new 'Build' script for 'Foo' version '0.01'

❯ ./Build
mkdir blib/lib
mkdir blib/arch
mkdir blib/bindoc
mkdir blib/libdoc
mkdir blib/script
mkdir blib/bin
cp lib/Foo.pm blib/lib/Foo.pm

❯ ./Build test
WARNING: Can't figure out install path for types: libdoc bindoc
Files will not be installed.
prove
t/00_use.t .. ok
All tests successful.
Files=1, Tests=1,  0 wallclock secs ( 0.00 usr  0.00 sys +  0.02 cusr  0.00 csys =  0.02 CPU)
Result: PASS

❯ ./Build install
WARNING: Can't figure out install path for types: libdoc bindoc
Files will not be installed.
install install_map HASH(0xbc1dd08a0)
Installing /Users/skaji/env/perl/versions/relocatable-5.42.0.0/lib/site_perl/5.42.0/Foo.pm
```

It seems that bindoc and libdoc are always being created here:
https://github.com/Leont/dist-build/blob/main/lib/Dist/Build.pm#L112-L113
Could you take another look at this?

**Comment by Leont** [comment]
That appears to be an ExtUtils::InstallPaths issue. I'm going to have to rethink that one (but fortunately it's not a serious issue).
